# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('author_username', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('sentiment_type', models.CharField(max_length=100)),
                ('sentiment_score', models.IntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
