# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Article',
        ),
    ]
